spring.application.name=sala-service
server.port=8084
spring.datasource.url=jdbc:mysql://localhost:3306/db_salas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true