# Nombre del microservicio y puerto de escucha
spring.application.name=api-gateway
server.port=8080

# Registro y descubrimiento en Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Habilita el localizador de descubrimiento por nombre de servicio
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-name=true

# 1. pelicula-service
spring.cloud.gateway.routes[0].id=pelicula-service
spring.cloud.gateway.routes[0].uri=lb://pelicula-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/peliculas/**

# 2. usuario-service
spring.cloud.gateway.routes[1].id=usuario-service
spring.cloud.gateway.routes[1].uri=lb://usuario-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/usuarios/**

# 3. auth-service
spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=lb://auth-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/auth/**

# 4. sala-service
spring.cloud.gateway.routes[3].id=sala-service
spring.cloud.gateway.routes[3].uri=lb://sala-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/salas/**

# 5. funcion-service
spring.cloud.gateway.routes[4].id=funcion-service
spring.cloud.gateway.routes[4].uri=lb://funcion-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/funciones/**

# 6. asiento-service
spring.cloud.gateway.routes[5].id=asiento-service
spring.cloud.gateway.routes[5].uri=lb://asiento-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/asientos/**

# 7. reserva-service
spring.cloud.gateway.routes[6].id=reserva-service
spring.cloud.gateway.routes[6].uri=lb://reserva-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/reservas/**

# 8. snack-service
spring.cloud.gateway.routes[7].id=snack-service
spring.cloud.gateway.routes[7].uri=lb://snack-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/snacks/**

# 9. orden-service
spring.cloud.gateway.routes[8].id=orden-service
spring.cloud.gateway.routes[8].uri=lb://orden-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/ordenes/**

# 10. notificacion-service
spring.cloud.gateway.routes[9].id=notificacion-service
spring.cloud.gateway.routes[9].uri=lb://notificacion-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/notificaciones/**
